# -*- coding: utf-8 -*-
"""ingest_places.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJm8t4YjR81vIbDYgZ_ZWKnXTvC8qm8h
"""

import pandas as pd

# -------------------------------------------------------
# CDC PLACES Ingestion Script
# Source: PLACES Local Data for Better Health, County Data
# -------------------------------------------------------

# --- STEP 1: Load raw data ---
RAW_FILE_PATH = "/PLACES__Local_Data_for_Better_Health,_County_Data,_2025_release_20260322.csv"
df = pd.read_csv(RAW_FILE_PATH)
print(f"Raw data loaded: {df.shape[0]} rows, {df.shape[1]} columns")

# --- STEP 2: Filter rows ---

# MeasureIds we care about
MEASURE_IDS = [
    "DIABETES",
    "OBESITY",
    "BPHIGH",
    "LPA",
    "CSMOKING",
    "CHECKUP",
    "CHD",
    "KIDNEY",
    "SLEEP",
    "MHLTH"
]

# Keep only crude prevalence for consistency
VALUE_TYPE = "CrdPrv"

df_filtered = df[
    (df["MeasureId"].isin(MEASURE_IDS)) &
    (df["DataValueTypeID"] == VALUE_TYPE)
]

print(f"After filtering: {df_filtered.shape[0]} rows")

# --- STEP 2b: Keep only columns we need ---
COLUMNS_TO_KEEP = [
    "Year",
    "StateAbbr",
    "StateDesc",
    "LocationName",
    "LocationID",       # fips code
    "MeasureId",
    "Data_Value",
    "Low_Confidence_Limit",
    "High_Confidence_Limit",
    "TotalPopulation",
    "Geolocation"
]

df_filtered = df_filtered[COLUMNS_TO_KEEP]

# --- STEP 3: Pivot to wide format ---
# One row per county per year, one column per measure
df_wide = df_filtered.pivot_table(
    index=["Year", "StateAbbr", "StateDesc", "LocationName", "LocationID", "TotalPopulation", "Geolocation"],
    columns="MeasureId",
    values="Data_Value"
).reset_index()
df_wide.columns.name = None

# Rename measure columns to be cleaner
df_wide = df_wide.rename(columns={
    "DIABETES":  "diabetes_pct",
    "OBESITY":   "obesity_pct",
    "BPHIGH":    "bphigh_pct",
    "LPA":       "lpa_pct",
    "CSMOKING":  "smoking_pct",
    "CHECKUP":   "checkup_pct",
    "CHD":       "chd_pct",
    "KIDNEY":    "kidney_pct",
    "SLEEP":     "sleep_pct",
    "MHLTH":     "mhlth_pct",
    "LocationID": "fips_code",
    "Year":       "report_year"
})

df_wide["county_year_id"] = df_wide["fips_code"].astype(str) + "_" + df_wide["report_year"].astype(str)

print(f"Wide format: {df_wide.shape[0]} rows, {df_wide.shape[1]} columns")
print(df_wide.head())

import os
os.makedirs("data/processed", exist_ok=True)
# --- STEP 4: Save clean output ---
OUTPUT_PATH = "data/processed/county_facts.csv"
df_wide.to_csv(OUTPUT_PATH, index=False)
print(f"Saved to {OUTPUT_PATH}")

print(df_wide.shape)
df_wide.head()